### ISSUE TITLE
Instructions for use

### ISSUE THREAD

**Issue by HkDzl** [ohayoyogi/blender-exporter-colmap#1]
Thank you very much for your contribution, but I don't know how to use it. Could you please briefly explain its usage? Looking forward to your reply!

**Comment by ohayoyogi** [comment]
Hi HkDzl. Thank you for writing issue.
I added some instructions for use.

Feel free to reopen this issue if you have some question about it.

**Comment by HkDzl** [comment]
Oh, I see it. Thank you very much for your instructions!
