### ISSUE TITLE
Save the .bin file instead of .txt file?

### ISSUE THREAD

**Issue by yyyhz** [ohayoyogi/blender-exporter-colmap#3]
I wonder could I save the .bin file instead of .txt file?

**Comment by yyyhz** [comment]
And also I wonder could I save the .bin file instead of .txt file?

**Comment by ohayoyogi** [comment]
I do not know about the binary format, so I cannot make it support .bin file.
Sorry for inconvenience.

Contribution is welcome!

**Comment by wooni-github** [comment]
@yyyhz 

You can simply convert .txt files to .bin files by using command like

`colmap model_converter --input_path . --output_path . --output_type BIN`
